### ISSUE TITLE
build failure due to network error

### ISSUE THREAD

**Issue by elbraulio** [elbraulio/clcert-beacon-observer#12]
```
Running com.elbraulio.clcert.beacon.impl.BeaconHttpRequestTest
[562](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:563)
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 62.138 sec <<< FAILURE!
[563](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:564)
get_close_client_after_usage(com.elbraulio.clcert.beacon.impl.BeaconHttpRequestTest)  Time elapsed: 61.367 sec  <<< ERROR!
[564](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:565)
java.lang.Exception: Unexpected exception, expected<java.lang.IllegalStateException> but was<com.elbraulio.clcert.beacon.exception.ClcertBeaconObserverException>
[565](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:566)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:30)
[566](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:567)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[567](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:568)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
[568](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:569)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
[569](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:570)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
[570](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:571)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
[571](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:572)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
[572](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:573)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
[573](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:574)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
[574](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:575)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
[575](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:576)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
[576](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:577)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[577](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:578)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
[578](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:579)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
[579](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:580)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
[580](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:581)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
[581](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:582)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[582](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:583)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[583](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:584)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[584](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:585)
	at java.lang.reflect.Method.invoke(Method.java:498)
[585](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:586)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
[586](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:587)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
[587](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:588)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
[588](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:589)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
[589](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:590)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
[590](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:591)
Caused by: com.elbraulio.clcert.beacon.exception.ClcertBeaconObserverException: unexpected status code [504]
[591](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:592)
	at com.elbraulio.clcert.beacon.impl.BeaconHttpRequest.get(BeaconHttpRequest.java:54)
[592](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:593)
	at com.elbraulio.clcert.beacon.impl.BeaconHttpRequestTest.get_close_client_after_usage(BeaconHttpRequestTest.java:35)
[593](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:594)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[594](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:595)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[595](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:596)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[596](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:597)
	at java.lang.reflect.Method.invoke(Method.java:498)
[597](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:598)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
[598](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:599)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[599](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:600)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
[600](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:601)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[601](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:602)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
[602](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:603)
	... 24 more
[603](https://github.com/elbraulio/clcert-beacon-observer/actions/runs/4494359915/jobs/7906747435#step:4:604)
```

**Comment by elbraulio** [comment]
caused by server timeout
